[[redirects]]
  from = "/api/*"
  to = "https://smart-office-document-assistant-yonim.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://smart-office-document-assistant-yonim.onrender.com/auth/:splat"
  status = 200
  force = true